image: harbor.novascotia.ca/cts/devops-cicd:latest

variables:
  REGISTRY_HOST: harbor.novascotia.ca
  CONTAINER_BUILD_IMAGE: ${REGISTRY_HOST}/digitalplatformservices/identity/indy-sdk-builder:${CI_COMMIT_SHORT_SHA}
  CONTAINER_PROD_IMAGE: ${REGISTRY_HOST}/digitalplatformservices/identity/indy-sdk-builder:latest


stages:
  - build


Build Indy: 
  image: ${REGISTRY_HOST}/digitalplatformservices/identity/indy-sdk-builder:latest
  stage: build
  script:
  - echo "Current Directory"
  - pwd
  - echo "Home is ${HOME}"
  - echo "path is ${PATH}"
  - cd libindy
  - cargo build --release
  - cp target/*/libindy.so "$HOME/.local/lib"
  - cd ../cli
  - cargo build --release 
  - cp target/*/indy-cli "$HOME/.local/bin"
  - cd ../experimental/plugins/postgres_storage/
  - cargo build --release 
  - cp target/*/libindystrgpostgres.so "$HOME/.local/lib"
  - echo "ls -l /home/indy/.local/lib"
  - ls -l /home/indy/.local/lib
  - echo "ls -l /home/indy/.local/bin"
  - ls -l /home/indy/.local/bin
  artifacts:
    paths:
    - /home/indy/.local/lib/*
    - /home/indy/.local/bin/*